server:
  port: 8082

spring:
  application:
    name: ms-sucursales
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/db_ms_sucursales?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format:
          sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html